### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by TrySound** [TrySound/skrollr-decks#1]
- [x] Add callback option
- [x] Add active class to segment and navigation item
- [x] Auto add id to segment
- [x] goto method
- [x] Test in mobile browsers
- [x] Add scroll to deck time option

**Comment by 123ndy** [comment]
**New idea:** 
Make an option so that the autoscroll scrolls to the deck that fills up most of the screen, and not just to the next deck if it only displays a couple of pixels. (A user sometimes scrolls just a little to far and get some of the pixels of the next deck inside the window, it can be annoying if the page then scrolls to the next deck instead of centering in on the above deck that fills up most of the screen). 

Did you understand what I meant? :)

**Comment by TrySound** [comment]
I make offset option. It's works in percents.
What do you think about new version?

**Comment by 123ndy** [comment]
Great! I will try the new version soon and give you feedback :)
